config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :reviews
  resources :portfolios
  resources :stocks, only: [:new, :create] do
    resources :investments
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  # delete 'logout', to: "sessions#destroy", as "logout"
  post 'reviews/new', to: 'reviews#new'

  # get "/login", to: "sessions#new"
  # post "/login", to: "sessions#create"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    belongs_to :user
    has_many :reviews
    has_many :investments
    has_many :stocks, through: :investments

    
    def array_data 
        data = []
        stocks.each_with_index do |s,i|
            chunk = []
            chunk << s.stock_name
            chunk << s.current_price
            chunk << self.investments[i].purchase_price
            chunk << self.investments[i].num_of_shares
            data << chunk
        end 
        data
    end 
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    before_action :find_portfolio, only: [:show, :edit, :update, :destroy]

    def index

        @portfolios = User.find(params[:user_id]).portfolios

    end

    def show
    
    end 

    def new
        @portfolio = Portfolio.new
        @users = User.all
    end

    def create
        @portfolio = Portfolio.create(portfolio_params)
        redirect_to user_path(@portfolio.user)
    end

    def edit
        
    end

    def update
        @portfolio.update(portfolio_params)
        redirect_to @portfolio
    end

    def destroy
        @portfolio.destroy
        redirect_to users_path
    end

    private

    def portfolio_params
        params.require(:portfolio).permit(:portfolio_name, :initial_cash, :user_id)
    end

    def find_portfolio
        @portfolio = Portfolio.find(params[:id])
        @data = @portfolio.array_data
    end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for @portfolio do |f| %>
    <%= f.label :portfolio_name %>
    <%= f.text_field :portfolio_name %>

    <%= f.label :initial_cash %>
    <%= f.number_field :initial_cash %>

    <%= f.label :user_id %>
    <%= f.collection_select :user_id, @users, :id, :full_name, prompt: true %>
    
    <%= f.submit %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Please update the current Portfolio</h1>

<%= render 'form' %>

app/views/portfolios/index.html.erb
<h1>Welcome to Your Portfolio Index Page</h1>
<%= link_to  "Create a new portfolio", new_user_portfolio_path %>

<h5>Here are your portfolios: </h5>
<% @portfolios.each do |portfolio| %>
   <p><%= link_to portfolio.portfolio_name, user_portfolio_path(portfolio.user,portfolio) %></p> 
<% end %>

app/views/portfolios/new.html.erb
<h1>Please create a new Portfolio</h1>

<%= render 'form' %>

app/views/portfolios/show.html.erb
<h1>Portfolio Name: <%= @portfolio.portfolio_name %> </h1>
<%= link_to  "Add Investment", new_stock_path %>
<h3>Here are all your investments for this portfolio:</h3>
<table>
<tr>
<th>Stock Name </th>
<th>Current Price </th>
<th>Purchased Price</th>
<th>Number of shares owned</th>
</tr>
<tr>
<% @data.each do |d| %>
    <td> <%= d.first %> </td>
    <td> $<%=d.second  %> </td>
    <td> $<%=d.third  %> </td>
    <td> <%=d.fourth  %> </td>
</tr>
<% end %>
</table>
<h1>These are the current reviews of this portfolio</h1>
<ol>
<% @portfolio.reviews.each do |review| %>
    <h3>Title: <%= review.title %></h3>
    <p><%= review.content %></p>
    <p>Ratings: <%= review.ratings %></p>
    <%= button_to  "Delete this review", review_path(review), method: :delete %>
<% end %>
</ol>
<%= link_to  "Return to Main Menu", users_path %>
<%= button_to  "Add a review for this Portfolio", new_review_path, method: :new, params: {portfolio_id: @portfolio.id} %>
<%= button_to "Delete this Portfolio", portfolio_path(@portfolio), method: :delete %>