config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :reviews
  resources :portfolios
  resources :stocks, only: [:new, :create] do
    resources :investments
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  # delete 'logout', to: "sessions#destroy", as "logout"
  post 'reviews/new', to: 'reviews#new'

  # get "/login", to: "sessions#new"
  # post "/login", to: "sessions#create"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :portfolios
    has_many :investments, through: :portfolios
    has_many :stocks, through: :portfolios
    attr_reader :password

    def full_name
        full_name = "#{first_name} #{last_name}"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # has_secure_password
    # attr_reader :password
    before_action :find_user, only: [:show, :edit, :update, :destroy]

    def index
        @users = User.all
    end

    def show

    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user)
    end

    def edit

    end 
    
    def update
        @user.update(user_params)
        redirect_to @user
    end

    def destroy
        @user.destroy
        redirect_to users_path
    end

    # def password=(plain_text_pw)
    #     self.password_digest = BCrypt::Password.create(plain_text_pw)
    # end

    # def authenticate
    #     if BCrypt::Password.new(self.password_digest) == ptpw
    #         @user
    #     else
    #         false
    #     end
    # end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :user_name, :password, :email)
    end

    def find_user
        @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Please make the changes</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 style= "color:darkred;">Welcome to "Cash Me Outside"</h1>
<% @users.each do |user| %>
    <p><%= link_to user.full_name, user%><p>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for User.new do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :user_name %>
  <%= f.text_field :user_name %>

  <%= f.label :password %>
  <%= f.text_field :password %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.submit %>


<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.full_name %></h1>
<h5><%= link_to "Create a new portfolio", new_portfolio_path %></h5>
<h3>You currently have these portfolios:</h3>

<table>
<tr>
<th>Portfolio Name </th>
<th>Initial Cash </th>
</tr>
<tr>
<% @user.portfolios.each do |portfolio|%>
    <td><%= link_to portfolio.portfolio_name, portfolio%>
    <td> $<%= portfolio.initial_cash  %></td>
</tr>
<% end %>
</table>